
[loom]
version = "0.5.0"
project-type = "python"

[loom.types.patch]
symbol = "ğŸ“œ"
increment = "0.0.1"
publish = false

[loom.types.minor]
symbol = "âœ…"
increment = "0.1.0"
publish = true

[loom.types.major]
symbol = "ğŸ“¦"
increment = "1.0.0"
publish = true

[loom.types.chore]
symbol = "ğŸ”¨"
increment = "0.0.0"
publish = false
